---
title: "Activity Correctess"
author: "Sasmito Adibowo"
date: "20 February 2015"
output: html_document
mainfont: Palatino
sansfont: Lucida Grande
monofont: Menlo 
---

## Setup



```{r,message=FALSE}
library(plyr)
library(dplyr)
library(data.table)
library(lubridate)
library(caret)
library(zoo)
library(doMC)
registerDoMC(cores = 4)
```

Data Loading and cleaning

```{r}
remove(activityValidation,activityTrain)
downloadData <- function(tableName,sourceURL) {
    envirPos <- 1
    baseFolder <- "data"
    downloadFilePath <- file.path(baseFolder,paste(tableName,"csv",sep="."))
    downloadTablePath <- file.path(baseFolder,paste(tableName,"rds",sep="."))
    if(!exists(tableName)) {
        if(!file.exists(downloadTablePath)) {
            if(!file.exists(downloadFilePath)) {
                download.file(sourceURL,destfile=downloadFilePath)
            }
            readTable <- fread(downloadFilePath)
            saveRDS(readTable,file=downloadTablePath)
        } else {
            readTable <- readRDS(downloadTablePath)
        }
        assign(tableName,readTable,pos=envirPos)
    }
}
downloadData("activityValidation","http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv")
downloadData("activityTrain","http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")

inputTrain <- activityTrain %>% 
    mutate(V1=as.integer(V1), user_name=factor(user_name), cvtd_timestamp=dmy_hms(cvtd_timestamp), new_window=factor(new_window), classe=factor(classe)) %>% setkey(V1)
inputValidation <- activityValidation %>% mutate(V1=as.integer(V1),user_name=factor(user_name), cvtd_timestamp=dmy_hms(cvtd_timestamp),new_window=factor(new_window), problem_id=factor(problem_id)) %>% setkey(V1)

```

Force numeric, carry forward `NA` values, and finally replace `NA` values with zeros.

```{r}
featureColumnIndexes <- 9:159

cleanInput <- function(inputTable) {
    na.replace <- function(x,r) {
        ifelse(!is.na(x),x,r)
    }
    featureColumnNames <- names(inputTable)[featureColumnIndexes]
    mutateExpression <- paste("mutate(inputTable,",paste(featureColumnNames,"=as.numeric(",featureColumnNames,")",sep="",collapse=","),")",sep="")    
    inputTable <- eval(parse(text=mutateExpression)) %>% na.locf
    mutateExpression <- paste("mutate(inputTable,",paste(featureColumnNames,"=na.replace(",featureColumnNames,",0)",sep="",collapse=","),")",sep="")
    inputTable <- data.frame(eval(parse(text=mutateExpression)))
    inputTable[,featureColumnIndexes] <- sapply(inputTable[,featureColumnIndexes],as.numeric)
    inputTable
}

inputTrain <- cleanInput(inputTrain)
inputValidation <- cleanInput(inputValidation)
```

You can also embed plots, for example:

```{r}
set.seed(42)
modelFormula <- as.formula(paste("classe ~",paste(names(inputTrain)[featureColumnIndexes],collapse="+")))
indexTraining <- createDataPartition(inputTrain$classe,p=0.6,list=FALSE)
trainingSet <- inputTrain[indexTraining,] 
testingSet<- inputTrain[-indexTraining,] 

#modfit <- train(form=modelFormula,preProcess="pca",method="rf",data=trainingSet)

```

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
